# include/dbt/dbt_project.yml
name: 'churn_prediction'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'churn_prediction'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  churn_prediction:
    # Applies to all files under models/staging/
    staging:
      +materialized: view
      +schema: churn_staging
    # Applies to all files under models/marts/
    marts:
      +materialized: table
      +schema: churn_marts

vars:
  # Define churn threshold in days
  churn_threshold_days: 30
  
  # Define minimum transaction amount for inclusion
  min_transaction_amount: 1

seeds:
  churn_prediction:
    +schema: churn_analytics

---

# include/dbt/profiles.yml  
churn_prediction:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: postgres
      password: postgres
      port: 5432
      dbname: postgres
      schema: public
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10
      retries: 1

---

# include/dbt/models/schema.yml
version: 2

sources:
  - name: public
    description: Data from PostgreSQL dump
    schema: public
    tables:
      - name: users
        description: User data from SQL dump
        columns:
          - name: user_id
            description: Unique user identifier
            tests:
              - unique
              - not_null
          - name: email
            description: User email address
            tests:
              - not_null
          - name: region
            description: User geographic region
          - name: signup_channel
            description: User acquisition channel
          - name: created_at
            description: User registration timestamp
            tests:
              - not_null

      - name: transactions
        description: User transaction history from SQL dump
        columns:
          - name: transaction_id
            description: Transaction ID (UUID)
            tests:
              - unique
              - not_null
          - name: user_id
            description: User identifier
            tests:
              - not_null
          - name: amount
            description: Transaction amount
            tests:
              - not_null
          - name: status
            description: Transaction status
            tests:
              - not_null
              - accepted_values:
                  values: ['success', 'failed', 'refunded']

  - name: churn_analytics
    description: Raw churn analytics data
    schema: churn_analytics
    tables:
      - name: raw_user_activities
        description: Raw user activity events from CSV
        columns:
          - name: user_id
            description: User identifier
            tests:
              - not_null
          - name: session_id
            description: Session identifier
            tests:
              - not_null
          - name: event_name
            description: Type of activity event
            tests:
              - not_null
          - name: event_timestamp
            description: When the event occurred
            tests:
              - not_null

models:
  - name: stg_users
    description: Cleaned and standardized user data
    columns:
      - name: user_id
        description: Unique user identifier
        tests:
          - unique
          - not_null
      - name: signup_date
        description: User registration timestamp
        tests:
          - not_null
      - name: standardized_region
        description: Standardized region name
        tests:
          - not_null
      - name: standardized_channel
        description: Standardized acquisition channel
        tests:
          - not_null

  - name: stg_transactions
    description: Cleaned and standardized transaction data
    columns:
      - name: transaction_id
        description: Unique transaction identifier
        tests:
          - unique
          - not_null
      - name: user_id
        description: User identifier
        tests:
          - not_null
      - name: amount_ngn
        description: Transaction amount in NGN
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0

  - name: stg_activities
    description: Cleaned and standardized activity data
    columns:
      - name: user_id
        description: User identifier
        tests:
          - not_null
      - name: session_id
        description: Session identifier
        tests:
          - not_null
      - name: standardized_event
        description: Standardized event name
        tests:
          - not_null

  - name: churn_features
    description: Final ML-ready churn prediction features
    columns:
      - name: user_id
        description: Unique user identifier
        tests:
          - unique
          - not_null
      - name: churn_flag
        description: Binary churn indicator (1=churned, 0=active)
        tests:
          - not_null
          - accepted_values:
              values: [0, 1]
      - name: total_spend_ngn
        description: Total amount spent by user (NGN)
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      - name: days_since_last_activity
        description: Days since last user activity
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      - name: rfm_total_score
        description: Total RFM score (3-15)
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 3
              max_value: 15

---

