# include/dbt/dbt_project.yml
name: 'retail_analytics'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'retail_analytics'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  retail_analytics:
    # Retail Analytics Models
    retail:
      staging:
        +materialized: view
        +schema: retail_staging
      marts:
        +materialized: table
        +schema: retail_marts
      analytics:
        +materialized: table
        +schema: retail_analytics

vars:
  # Retail Analytics Variables
  promo_discount_threshold: 0.10  # 10% discount threshold for promo detection
  promo_min_days: 1  # Minimum days for promo classification (lowered for short data periods)
  bidco_supplier_pattern: 'BIDCO%'  # Pattern to identify Bidco products

seeds:
  retail_analytics:
    +schema: retail_raw
