# include/dbt/dbt_project.yml
name: 'churn_prediction'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'churn_prediction'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  churn_prediction:
    # Applies to all files under models/staging/
    staging:
      +materialized: view
      +schema: churn_staging
    # Applies to all files under models/marts/
    marts:
      +materialized: table
      +schema: churn_marts

vars:
  # Define churn threshold in days
  churn_threshold_days: 30
  
  # Define minimum transaction amount for inclusion
  min_transaction_amount: 1

seeds:
  churn_prediction:
    +schema: churn_analytics
